spring.application.name=microservice-service
server.port=8086

# ?? DataSource ???????????????????????????????????????????????????????????????
spring.datasource.url=jdbc:mysql://localhost:3306/prolance_service?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ?? JPA / Hibernate ???????????????????????????????????????????????????????????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ?? Eureka Client ?????????????????????????????????????????????????????????????
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

# ?? Actuator ??????????????????????????????????????????????????????????????????

# ?? Error Handling ????????????????????????????????????????????????????????????
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
logging.level.com.example.microservice_service=DEBUG
gateway.url=http://localhost:8085
# Enable Feign circuit breaker support (required for fallbackFactory to activate)
spring.cloud.openfeign.circuitbreaker.enabled=true


jwt.secret=${JWT_SECRET}
# Prometheus monitoring
management.endpoints.web.exposure.include=health,prometheus,info,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
